### ISSUE TITLE
Usage with multiple Kibana instances in Kubernetes

### ISSUE THREAD

**Issue by weibeld** [chamilad/kibana-prometheus-exporter#14]
How does the exporter collect metrics if multiple Kibana instances are load-balanced by a Service in Kubernetes (Kibana URL is the domain name of the Service)?

Currently, I see only one instance of each metric in Prometheus, even though I have two Kibana instances. Does the exporter collect metrics through the Service and thus hits a different instance each time?

**Comment by chamilad** [comment]
Hi @weibeld , tbh this wasn't considered in the initial implementation. However I'm guessing we could easily incorporate this with a few initial API calls to 
1. figure out member count
2. populate metrics per member

Let me spend some time looking into details. Happy to accept a PR if you have one.

**Comment by chamilad** [comment]
Ok, I was way off in my guess the first time. There doesn't seem to be any distributed cluster formed between Kibana instances, so there is no single API endpoint in Kibana that can give us the details about the "cluster it has joined". 

One way to tackle this is to do some kind of platform specific discovery for the Kibana instances and their endpoints and have the exporter build the metrics based on that information. For platforms like K8s this would work, though there would have to be a ServiceAccount attached to the exporter for that to happen (extra function, extra complexity). I'd like this Container to run with no ServiceAccount at all.

Using the exporter as a side-car Container would work (an exporter per Kibana Pod). However the Prometheus scrape config would have to be tweaked a bit for that to work, maybe switch to `pod` role to map each Pod instead of a Service. I didn't use multiple Kibana instances, so I can't verify if this is a good approach, but I'm fairly certain pushing discovery to Prometheus, the layer that already does that is better.

Going down the path where the binary would handle this complexity doesn't seem like a good option for me at the moment. But I'm willing to see if you have alternative options. Please comment if you want to approach this issue in another way. I'll close it until then.
